### ISSUE TITLE
README.md is Google Chrome specific

### ISSUE THREAD

**Issue by tripulse** [alx365/rust-native-messaging-Web-API-example#1]
> For chrome, follow these steps:
> 1. go to chrome://extensions
> 2. Load unpacked
> 3. Choose folder and probably have to turn on developer mode before you can load unpacked in the top right in chrome://extensions

The steps to use this was only documented for Google Chrome, which is:
![absolutely_proprietary](https://user-images.githubusercontent.com/37257726/83751073-e0c2a280-a683-11ea-9ea0-09d451521494.jpg)

You should document for other open-source or free-software browsers too else, you (@alx365) is going to identify as either a "chrome shill" or a "corporate slave", so fix this ASAP.

**Comment by legendofmiracles** [comment]
The readme isn't chrome specific (it also has firefox instructions), fun fact, i never tested it in chrome, that steps are copied straight from the docs. 

Have a nice day
